import * as React from "react";
import * as UI from "@nextui-org/react";

export default function TwoAuthentication() {
    return (
        <UI.ModalContent>
            {(onClose) => (
                <>
                    <UI.ModalHeader className="flex flex-col gap-1">
                        <h1 className="text-2xl font-semibold text-center">
                            About Two-Factor Authentication
                        </h1>
                    </UI.ModalHeader>
                    <UI.ModalBody className="modal-content">
                        <section className="flex flex-col justify-center items-center max-w-md mx-auto h-full text-sm text-justify">
                            <p className="mt-4">
                                <strong>Two-factor authentication</strong>, (2FA) adds an
                                extra layer of security when logging into websites or
                                apps. With 2FA, you log in with your username and password
                                and provide another form of authentication that only you
                                have access to.
                            </p>

                            <p className="mt-2">
                                <strong>Note:</strong> Starting in March 2023 and through
                                the end of 2023, PeepUp will gradually begin to require
                                all users to enable one or more forms of two-factor
                                authentication (2FA).
                                <ol className="px-6 list-disc py-4">
                                    <li className="mb-4">
                                        If you are in an eligible group, you will receive
                                        a notification email when that group is selected
                                        for enrollment, marking the beginning of a 45-day
                                        2FA enrollment period, and you will see banners
                                        asking you to enroll in 2FA on PeepUp.com.
                                    </li>
                                    <li className="mb-4">
                                        If you don't receive a notification, then you are
                                        not part of a group required to enable 2FA, though
                                        we strongly recommend it.
                                    </li>
                                </ol>
                            </p>

                            <p className="mb-2">
                                For PeepUp, the second form of authentication is a code
                                generated by an application on your mobile device or sent
                                as a text message (SMS). After you enable 2FA, PeepUp
                                generates an authentication code any time someone attempts
                                to sign into your account on PeepUp.com. The only way
                                someone can sign into your account is if they know both
                                your password and have access to the authentication code
                                on your phone.
                            </p>

                            <p className="mb-4">
                                After configuring 2FA, using a time-based one-time
                                password (TOTP) mobile app, or via text message, you can
                                add a security key, such as a FIDO2 hardware security key,
                                Apple Touch ID, or Windows Hello. The technology that
                                enables authentication with a security key is called
                                WebAuthn. WebAuthn is the successor to U2F and works in
                                all modern browsers.
                            </p>
                        </section>
                    </UI.ModalBody>
                    <UI.ModalFooter></UI.ModalFooter>
                </>
            )}
        </UI.ModalContent>
    );
}
